TARGET = demo_lcd

CFLAGS += -O2

BSP_BASE = ../../bsp


C_SRCS := \
	demo_lcd.c\
        oled.c \
        ZK.c\

HEADERS := \
	bmp.h\
	oled.h \
	oledfont.h\

include $(BSP_BASE)/$(BOARD)/n22/env/common.mk
